# swagger configuration file

# values in the swagger hash are system configuration for swagger
swagger:
  mapErrorsToJson: true
  docEndpoints:
    raw: /swagger
logger:
  logLevel: debug
database:
  user: fleetster
  password: fleetster456
  host: localhost
  database: email_templates
  connectionLimit: 10
  acquireTimeout: 2000
# any other values in this file are just loaded into the config for application access...
