# swagger configuration file

# values in the swagger hash are system configuration for swagger
swagger:
  mapErrorsToJson: true
  docEndpoints:
    raw: /swagger
logger:
  logLevel: info
# any other values in this file are just loaded into the config for application access...
